// Professional academic CV template.
// Reads data from cv_data.yml (generated by bin/compile_cv_pdf.rb).

#let data = yaml("cv_data.yml")

// ── Page setup ────────────────────────────────────────────────────────────────

#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2cm, left: 2.2cm, right: 2.2cm),
  footer: context [
    #set text(size: 8pt, fill: luma(130))
    #align(center)[
      #data.name
      #h(0.6em)—#h(0.6em)
      Page #counter(page).display() of #counter(page).final().first()
    ]
  ],
)

#set text(font: "New Computer Modern", size: 10.5pt, lang: "en")
#set par(justify: true, leading: 0.62em)

// ── Helpers ───────────────────────────────────────────────────────────────────

#let section-rule(title) = {
  v(0.9em)
  text(weight: "bold", size: 10.5pt, tracking: 0.8pt, upper(title))
  v(0.1em, weak: true)
  line(length: 100%, stroke: 0.45pt + luma(60))
  v(0.3em)
}

// Return "" for null/empty values; otherwise str(int(v)).
#let yr(v) = {
  if v == none or v == "" { "" }
  else { str(int(v)) }
}

// "2023–" for open-ended, "2021" for single year, "2021–2023" for ranges.
#let yr-range(s, e) = {
  let a = yr(s)
  let b = yr(e)
  if b == ""     { a + "–" }
  else if a == b { a }
  else           { a + "–" + b }
}

// Two-column entry row.
#let entry-header(left-top, left-bot, right-top, right-bot) = {
  grid(
    columns: (1fr, auto),
    column-gutter: 0.5em,
    [
      *#left-top*
      #if left-bot != none and left-bot != "" [ \ #emph(left-bot)]
    ],
    align(right)[
      #if right-top != none and right-top != "" [*#right-top*]
      #if right-bot != none and right-bot != "" [ \ #text(size: 9.5pt, right-bot)]
    ],
  )
}

// ── Header ────────────────────────────────────────────────────────────────────

#align(center, {
  text(size: 22pt, weight: "bold", upper(data.name))
  linebreak()
  emph(data.label)
  linebreak()
  v(0.2em, weak: true)
  let contact = data.email + "  |  " + data.location
  let gh = data.at("github", default: "")
  if gh != "" { contact = contact + "  |  github.com/" + gh }
  text(size: 9.5pt, contact)
})

v(0.3em)

// ── Research Interests ────────────────────────────────────────────────────────

#if data.at("summary", default: "") != "" {
  section-rule("Research Interests")
  emph(data.summary)
}

// ── Education ─────────────────────────────────────────────────────────────────

#if data.at("education", default: ()).len() > 0 {
  section-rule("Education")
  for edu in data.education {
    entry-header(
      edu.institution,
      edu.degree + " in " + edu.area,
      yr-range(edu.at("start_year", default: none), edu.at("end_year", default: none)),
      edu.at("location", default: ""),
    )
    let hl = edu.at("highlights", default: ())
    if hl.len() > 0 {
      v(0.1em, weak: true)
      for item in hl { pad(left: 0.6em)[#sym.bullet #item] }
    }
    v(0.5em)
  }
}

// ── Experience helper ─────────────────────────────────────────────────────────

#let render-experience(entries) = {
  for entry in entries {
    entry-header(
      entry.company,
      entry.position,
      yr-range(entry.at("start_year", default: none), entry.at("end_year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: "")
    if s != "" {
      v(0.1em, weak: true)
      pad(left: 0.6em, text(s))
    }
    v(0.5em)
  }
}

// ── Research Experience ───────────────────────────────────────────────────────

#if data.at("research_experience", default: ()).len() > 0 {
  section-rule("Research Experience")
  render-experience(data.research_experience)
}

// ── Industry Experience ───────────────────────────────────────────────────────

#if data.at("industry_experience", default: ()).len() > 0 {
  section-rule("Industry Experience")
  render-experience(data.industry_experience)
}

// ── Teaching Experience ───────────────────────────────────────────────────────

#if data.at("teaching_experience", default: ()).len() > 0 {
  section-rule("Teaching Experience")
  for entry in data.teaching_experience {
    entry-header(
      entry.institution,
      entry.role + ", " + entry.course,
      yr(entry.at("start_year", default: none)),
      entry.at("location", default: ""),
    )
    v(0.45em)
  }
}

// ── Publications ──────────────────────────────────────────────────────────────

#let render-pubs(pubs) = {
  for (i, pub) in pubs.enumerate() {
    let authors = pub.authors.join(", ")
    let year    = yr(pub.at("year",    default: none))
    let journal = pub.at("journal",    default: "")
    let url     = pub.at("url",        default: "")

    // Build the trailing venue+year string in code mode to avoid . parsing issues.
    let venue-str = if journal != "" and year != "" {
      journal + " (" + year + ")."
    } else if journal != "" {
      journal + "."
    } else if year != "" {
      "(" + year + ")."
    } else {
      "."
    }

    let title-content = if url != "" {
      link(url, emph(pub.title))
    } else {
      emph(pub.title)
    }

    pad(left: 1.8em)[
      #place(left, dx: -1.8em)[
        #text(size: 9pt, weight: "bold")[\[#str(i + 1)\]]
      ]
      #text(size: 9.5pt)[#(authors + ". ") #title-content #venue-str]
    ]
    v(0.3em)
  }
}

#if data.at("first_author_publications", default: ()).len() > 0 {
  section-rule("First-Author Publications")
  render-pubs(data.first_author_publications)
}

#if data.at("co_author_publications", default: ()).len() > 0 {
  section-rule("Co-Author Publications")
  render-pubs(data.co_author_publications)
}

// ── Honors and Awards ─────────────────────────────────────────────────────────

#if data.at("awards", default: ()).len() > 0 {
  section-rule("Honors and Awards")
  for award in data.awards {
    entry-header(
      award.name,
      award.awarder,
      yr(award.at("year", default: none)),
      none,
    )
    v(0.4em)
  }
}

// ── Leadership and Service ────────────────────────────────────────────────────

#if data.at("leadership_service", default: ()).len() > 0 {
  section-rule("Leadership and Service")
  for entry in data.leadership_service {
    entry-header(
      entry.title,
      entry.organization,
      yr-range(entry.at("start_year", default: none), entry.at("end_year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: "")
    if s != "" {
      v(0.1em, weak: true)
      pad(left: 0.6em, text(s))
    }
    v(0.45em)
  }
}

// ── Outreach ──────────────────────────────────────────────────────────────────

#if data.at("outreach", default: ()).len() > 0 {
  section-rule("Outreach")
  for entry in data.outreach {
    entry-header(
      entry.title,
      entry.organization,
      yr(entry.at("year", default: none)),
      entry.at("location", default: ""),
    )
    v(0.4em)
  }
}

// ── Professional Presentations ────────────────────────────────────────────────

// Renders one subsection (invited / contributed / posters).
#let render-talks(talks) = {
  for talk in talks {
    v(0.2em, weak: true)
    // Primary bullet with talk title in italics.
    pad(left: 1em)[
      #place(left, dx: -1em)[#sym.bullet]
      #emph(["] + talk.title + ["])
    ]
    // Nested venue lines.
    for venue in talk.at("venues", default: ()) {
      let vname = venue.at("venue",    default: "")
      let loc   = venue.at("location", default: "")
      let year  = yr(venue.at("year",  default: none))
      let award = venue.at("award",    default: none)
      let emph2 = venue.at("emphasis", default: none)

      // Build display string in code mode.
      let parts = (vname,)
      if loc  != ""                    { parts.push(loc) }
      if year != ""                    { parts.push(year) }
      if award != none and award != "" { parts.push("(" + award + ")") }
      if emph2 != none and emph2 != "" { parts.push("(" + emph2 + ")") }

      pad(left: 2.2em)[
        #place(left, dx: -1.2em)[--]
        #parts.join(" | ")
      ]
      v(0.1em, weak: true)
    }
    v(0.15em)
  }
}

#let pres        = data.at("presentations",       default: (:))
#let invited     = pres.at("invited_talks",        default: ())
#let contributed = pres.at("contributed_talks",    default: ())
#let posters     = pres.at("contributed_posters",  default: ())

#if invited.len() > 0 or contributed.len() > 0 or posters.len() > 0 {
  section-rule("Professional Presentations")

  if invited.len() > 0 {
    text(weight: "bold", style: "italic", "Invited Talks")
    render-talks(invited)
  }

  if contributed.len() > 0 {
    v(0.3em)
    text(weight: "bold", style: "italic", "Contributed Talks")
    render-talks(contributed)
  }

  if posters.len() > 0 {
    v(0.3em)
    text(weight: "bold", style: "italic", "Contributed Posters")
    render-talks(posters)
  }
}

// ── Skills ────────────────────────────────────────────────────────────────────

#if data.at("skills", default: ()).len() > 0 {
  section-rule("Skills")
  for skill in data.skills {
    [*#(skill.label)*: #(skill.keywords)]
    linebreak()
  }
}
