// Professional academic CV template
// Data is read from cv_data.yml, generated by bin/compile_cv_pdf.rb

#let data = yaml("cv_data.yml")

// ── Page setup ───────────────────────────────────────────────────────────────

#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2cm, left: 2.2cm, right: 2.2cm),
  footer: context {
    set text(size: 8pt, fill: luma(130))
    align(center)[
      #data.name
      #h(0.6em)—#h(0.6em)
      Page #counter(page).display() of #counter(page).final().first()
    ]
  },
)

#set text(font: "New Computer Modern", size: 10.5pt, lang: "en")
#set par(justify: true, leading: 0.62em, spacing: 0.62em)

// ── Helpers ───────────────────────────────────────────────────────────────────

#let section-rule(title) = {
  v(0.85em, weak: false)
  block(width: 100%, spacing: 0pt, {
    text(weight: "bold", size: 10.5pt, tracking: 0.8pt)[#upper(title)]
    v(0.18em, weak: true)
    line(length: 100%, stroke: 0.45pt + luma(60))
  })
  v(0.3em, weak: false)
}

#let yr(v) = {
  if v == none or v == "" { "" }
  else { str(int(v)) }
}

#let yr-range(s, e) = {
  let a = yr(s)
  let b = yr(e)
  if b == ""      { a + "--"     }
  else if a == b  { a            }
  else            { a + "--" + b }
}

// Two-column entry header: description left, date/location right
#let entry-header(left-top, left-bot, right-top, right-bot) = {
  grid(
    columns: (1fr, auto),
    column-gutter: 0.6em,
    {
      text(weight: "bold")[#left-top]
      if left-bot != none and left-bot != "" {
        linebreak()
        text(style: "italic")[#left-bot]
      }
    },
    align(right, {
      if right-top != none and right-top != "" {
        text(weight: "bold")[#right-top]
      }
      if right-bot != none and right-bot != "" {
        linebreak()
        text(size: 9.5pt)[#right-bot]
      }
    }),
  )
}

// ── Header ────────────────────────────────────────────────────────────────────

#align(center)[
  #text(size: 22pt, weight: "bold", tracking: 0.5pt)[#data.name]
  #v(0.25em, weak: true)
  #text(size: 10.5pt, style: "italic")[#data.label]
  #v(0.3em, weak: true)
  #text(size: 9.5pt)[
    #data.email
    #h(0.7em)|#h(0.7em)
    #data.location
    #if data.at("github", default: "") != "" [
      #h(0.7em)|#h(0.7em)github.com/#data.github
    ]
  ]
]

// ── Research Interests ────────────────────────────────────────────────────────

#if data.at("summary", default: "") != "" {
  section-rule("Research Interests")
  text(style: "italic")[#data.summary]
}

// ── Education ─────────────────────────────────────────────────────────────────

#if data.at("education", default: ()).len() > 0 {
  section-rule("Education")
  for edu in data.education {
    entry-header(
      edu.institution,
      edu.degree + " in " + edu.area,
      yr-range(edu.at("start_year", default: none), edu.at("end_year", default: none)),
      edu.at("location", default: ""),
    )
    let hl = edu.at("highlights", default: ())
    if hl.len() > 0 {
      v(0.15em, weak: true)
      for h in hl {
        pad(left: 0.6em)[#sym.bullet #h]
      }
    }
    v(0.5em)
  }
}

// ── Research Experience ───────────────────────────────────────────────────────

#let render-experience(entries) = {
  for entry in entries {
    entry-header(
      entry.company,
      entry.position,
      yr-range(entry.at("start_year", default: none), entry.at("end_year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: "")
    if s != "" {
      v(0.15em, weak: true)
      pad(left: 0.6em)[#s]
    }
    v(0.5em)
  }
}

#if data.at("research_experience", default: ()).len() > 0 {
  section-rule("Research Experience")
  render-experience(data.research_experience)
}

#if data.at("industry_experience", default: ()).len() > 0 {
  section-rule("Industry Experience")
  render-experience(data.industry_experience)
}

// ── Teaching Experience ───────────────────────────────────────────────────────

#if data.at("teaching_experience", default: ()).len() > 0 {
  section-rule("Teaching Experience")
  for entry in data.teaching_experience {
    entry-header(
      entry.institution,
      entry.role + ", " + entry.course,
      yr(entry.at("start_year", default: none)),
      entry.at("location", default: ""),
    )
    v(0.45em)
  }
}

// ── Publications ──────────────────────────────────────────────────────────────

#let render-pubs(pubs) = {
  for (i, pub) in pubs.enumerate() {
    let authors = pub.authors.join(", ")
    let year    = yr(pub.at("year", default: none))
    let journal = pub.at("journal", default: "")
    let url     = pub.at("url", default: "")

    pad(left: 1.6em, {
      // hanging indent: index floats left
      place(left, dx: -1.6em)[#text(size: 9.5pt, weight: "bold")[[#str(i + 1)]]]
      text(size: 9.5pt)[#authors. ]
      if url != "" {
        link(url)[#text(size: 9.5pt, style: "italic")[#pub.title]]
      } else {
        text(size: 9.5pt, style: "italic")[#pub.title]
      }
      text(size: 9.5pt)[
        #if journal != "" [ #journal ]
        #if year    != "" [ (#year). ]
        #if journal == "" and year == "" [.]
      ]
    })
    v(0.3em)
  }
}

#if data.at("first_author_publications", default: ()).len() > 0 {
  section-rule("First-Author Publications")
  render-pubs(data.first_author_publications)
}

#if data.at("co_author_publications", default: ()).len() > 0 {
  section-rule("Co-Author Publications")
  render-pubs(data.co_author_publications)
}

// ── Honors and Awards ─────────────────────────────────────────────────────────

#if data.at("awards", default: ()).len() > 0 {
  section-rule("Honors and Awards")
  for award in data.awards {
    entry-header(
      award.name,
      award.awarder,
      yr(award.at("year", default: none)),
      none,
    )
    v(0.4em)
  }
}

// ── Leadership and Service ────────────────────────────────────────────────────

#if data.at("leadership_service", default: ()).len() > 0 {
  section-rule("Leadership and Service")
  for entry in data.leadership_service {
    entry-header(
      entry.title,
      entry.organization,
      yr-range(entry.at("start_year", default: none), entry.at("end_year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: "")
    if s != "" {
      v(0.15em, weak: true)
      pad(left: 0.6em)[#s]
    }
    v(0.45em)
  }
}

// ── Outreach ──────────────────────────────────────────────────────────────────

#if data.at("outreach", default: ()).len() > 0 {
  section-rule("Outreach")
  for entry in data.outreach {
    entry-header(
      entry.title,
      entry.organization,
      yr(entry.at("year", default: none)),
      entry.at("location", default: ""),
    )
    v(0.4em)
  }
}

// ── Professional Presentations ────────────────────────────────────────────────

#let render-talks(talks) = {
  for talk in talks {
    v(0.25em, weak: true)
    // Primary bullet: talk title
    pad(left: 0.8em, {
      place(left, dx: -0.8em)[#sym.bullet]
      text(style: "italic")["#talk.title"]
    })
    // Nested venue bullets
    let venues = talk.at("venues", default: ())
    if venues.len() > 0 {
      v(0.1em, weak: true)
      for venue in venues {
        let v-name = venue.at("venue",    default: "")
        let loc    = venue.at("location", default: "")
        let year   = yr(venue.at("year",  default: none))
        let award  = venue.at("award",    default: none)
        let emph   = venue.at("emphasis", default: none)

        pad(left: 2em, {
          place(left, dx: -1em)[--]
          v-name
          if loc  != ""   [ | #loc ]
          if year != ""   [ | #year ]
          if award != none and award != "" [ #h(0.2em)(#text(style: "italic")[#award]) ]
          if emph  != none and emph  != "" [ #h(0.2em)(#text(style: "italic")[#emph]) ]
        })
        v(0.1em, weak: true)
      }
    }
    v(0.2em)
  }
}

#let pres       = data.at("presentations",      default: (:))
#let invited    = pres.at("invited_talks",       default: ())
#let contributed = pres.at("contributed_talks",  default: ())
#let posters    = pres.at("contributed_posters", default: ())

#if invited.len() > 0 or contributed.len() > 0 or posters.len() > 0 {
  section-rule("Professional Presentations")

  if invited.len() > 0 {
    v(0.2em, weak: true)
    text(weight: "bold", style: "italic")[Invited Talks]
    render-talks(invited)
  }

  if contributed.len() > 0 {
    v(0.35em, weak: false)
    text(weight: "bold", style: "italic")[Contributed Talks]
    render-talks(contributed)
  }

  if posters.len() > 0 {
    v(0.35em, weak: false)
    text(weight: "bold", style: "italic")[Contributed Posters]
    render-talks(posters)
  }
}

// ── Skills ────────────────────────────────────────────────────────────────────

#if data.at("skills", default: ()).len() > 0 {
  section-rule("Skills")
  for skill in data.skills {
    [*#skill.label:* #skill.keywords]
    linebreak()
  }
}
