// Professional academic CV template.
// Reads data from cv_data.yml (generated by bin/compile_cv.py).

#let data = yaml("cv_data.yml")

// ── Page setup ────────────────────────────────────────────────────────────────

#set page(
  paper: "a4",
  margin: (top: 2cm, bottom: 2cm, left: 2.2cm, right: 2.2cm),
)

#set text(font: "New Computer Modern", size: 10.5pt, lang: "en")
#set par(justify: true, leading: 0.55em)

// ── Spacing constants ─────────────────────────────────────────────────────────

// Gap between separate entries in a section.
#let entry-gap = 0.65em
// Gap between the subtitle line and the body text / bullet list below it.
#let subtitle-body-gap = 0.15em
// Gap between individual bullet/highlight lines within one entry.
#let item-gap = 0.32em

// ── Helpers ───────────────────────────────────────────────────────────────────

#let section-rule(title) = {
  v(1.1em)
  text(weight: "bold", size: 10.5pt, tracking: 0.8pt, upper(title))
  v(0.1em, weak: true)
  line(length: 100%, stroke: 0.45pt + luma(60))
  v(0.4em)
}

#let yr(v) = {
  if v == none or v == "" { "" }
  else { str(int(v)) }
}

#let yr-range(s, e) = {
  let a = yr(s)
  let b = yr(e)
  if b == ""     { a + "–" }
  else if a == b { a }
  else           { a + "–" + b }
}

// Two-column header: left-top bold, left-bot italic, right plain.
// title-subtitle-gap controls vertical distance between the two left lines.
#let entry-header(left-top, left-bot, right-top, right-bot) = {
  grid(
    columns: (1fr, auto),
    column-gutter: 0.5em,
    row-gutter: 0.12em,
    [
      *#left-top*
      #if left-bot != none and left-bot != "" [ \ #emph(left-bot)]
    ],
    align(right)[
      #if right-top != none and right-top != "" [*#right-top*]
      #if right-bot != none and right-bot != "" [ \ #text(size: 9.5pt, right-bot)]
    ],
  )
}

// ── Header ────────────────────────────────────────────────────────────────────

#align(center, {
  text(size: 22pt, weight: "bold", upper(data.name))
  linebreak()
  emph(data.label)
  v(0.55em, weak: true)
  let contact = data.email + "  |  " + data.location
  let gh = data.at("github", default: "")
  if gh != "" { contact = contact + "  |  github.com/" + gh }
  text(size: 9.5pt, contact)
  linebreak()
  v(0.6em, weak: true)
  text(size: 8pt, fill: luma(100), "Last updated: " + data.at("last_updated", default: ""))
})

v(0.4em)

// ── Research Interests ────────────────────────────────────────────────────────

#if data.at("summary", default: "") != "" {
  section-rule("Research Interests")
  emph(data.summary)
}

// ── Education ─────────────────────────────────────────────────────────────────

#if data.at("education", default: ()).len() > 0 {
  section-rule("Education")
  for edu in data.education {
    entry-header(
      edu.institution,
      edu.degree + " in " + edu.area,
      yr-range(edu.at("start_year", default: none), edu.at("end_year", default: none)),
      edu.at("location", default: ""),
    )
    let hl = edu.at("highlights", default: ())
    if hl.len() > 0 {
      v(subtitle-body-gap)
      for item in hl {
        pad(left: 0.8em)[#sym.bullet #item]
        v(item-gap, weak: true)
      }
    }
    v(entry-gap)
  }
}

// ── Experience helper (position bold+italic, company plain) ───────────────────

#let render-experience(entries) = {
  for entry in entries {
    entry-header(
      entry.position,
      entry.company,
      yr-range(entry.at("start_year", default: none), entry.at("end_year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: "")
    if s != "" {
      v(subtitle-body-gap)
      pad(left: 0.8em, text(s))
    }
    v(entry-gap)
  }
}

// ── Research Experience ───────────────────────────────────────────────────────

#if data.at("research_experience", default: ()).len() > 0 {
  section-rule("Research Experience")
  render-experience(data.research_experience)
}

// ── Industry Experience ───────────────────────────────────────────────────────

#if data.at("industry_experience", default: ()).len() > 0 {
  section-rule("Industry Experience")
  render-experience(data.industry_experience)
}

// ── Teaching Experience ───────────────────────────────────────────────────────
// Roles in this set are collapsed into a single bold heading + bulleted list.
// All other roles are rendered as individual full entries.

#let grouped-teaching-roles = ("Teaching Assistant", "Guest Lecturer")

#if data.at("teaching_experience", default: ()).len() > 0 {
  section-rule("Teaching Experience")

  // Collect entries in order of first appearance per role.
  let role-order = ()
  let role-groups = (:)
  for entry in data.teaching_experience {
    let role = entry.role
    if role not in role-order { role-order.push(role) }
    if role in role-groups {
      role-groups.insert(role, role-groups.at(role) + (entry,))
    } else {
      role-groups.insert(role, (entry,))
    }
  }

  for role in role-order {
    let group = role-groups.at(role)
    if grouped-teaching-roles.contains(role) {
      // Grouped: bold role heading, one bullet per course.
      text(weight: "bold", role)
      v(subtitle-body-gap)
      for e in group {
        let year = yr(e.at("start_year", default: none))
        let loc  = e.at("location", default: "")
        let line = e.course + ", " + e.institution
        if loc  != "" { line = line + " | " + loc }
        if year != "" { line = line + " | " + year }
        pad(left: 0.8em)[#sym.bullet #line]
        v(item-gap, weak: true)
      }
      v(entry-gap)
    } else {
      // Individual entry: full header layout.
      let e = group.first()
      entry-header(
        role + ", " + e.course,
        e.institution,
        yr(e.at("start_year", default: none)),
        e.at("location", default: ""),
      )
      v(entry-gap)
    }
  }
}

// ── Publications ──────────────────────────────────────────────────────────────

// Bold "Burnham, Emilie" (or any variant matching the CV owner's name) in
// an author string and join authors with "; " instead of ", ".
#let format-authors(authors, owner-name) = {
  let parts = authors.map(a => {
    if a.contains(owner-name) or owner-name.contains(a) or a.starts-with("Burnham") {
      strong(a)
    } else {
      a
    }
  })
  parts.join("; ")
}

#let render-pubs(pubs) = {
  for (i, pub) in pubs.enumerate() {
    let year    = yr(pub.at("year",    default: none))
    let journal = pub.at("journal",    default: "")
    let url     = pub.at("url",        default: "")
    let owner   = data.at("name", default: "Burnham")
    // Use the last name for matching across author formats.
    let last    = owner.split(", ").first().split(" ").last()

    let formatted-authors = {
      let parts = pub.authors.map(a => {
        if a.starts-with(last) or a.contains(last) {
          strong(a)
        } else {
          a
        }
      })
      parts.join("; ")
    }

    let venue-str = if journal != "" and year != "" {
      journal + " (" + year + ")."
    } else if journal != "" {
      journal + "."
    } else if year != "" {
      "(" + year + ")."
    } else {
      "."
    }

    let title-content = if url != "" {
      link(url, emph(pub.title))
    } else {
      emph(pub.title)
    }

    pad(left: 1.8em)[
      #place(left, dx: -1.8em)[
        #text(size: 9pt, weight: "bold")[\[#str(i + 1)\]]
      ]
      #text(size: 9.5pt)[#formatted-authors. #title-content #venue-str]
    ]
    v(0.45em)
  }
}

#if data.at("first_author_publications", default: ()).len() > 0 {
  section-rule("First-Author Publications")
  render-pubs(data.first_author_publications)
}

#if data.at("co_author_publications", default: ()).len() > 0 {
  section-rule("Co-Author Publications")
  render-pubs(data.co_author_publications)
}

// ── Honors and Awards ─────────────────────────────────────────────────────────

#if data.at("awards", default: ()).len() > 0 {
  section-rule("Honors and Awards")
  for award in data.awards {
    entry-header(
      award.name,
      award.awarder,
      yr(award.at("year", default: none)),
      none,
    )
    let s = award.at("summary", default: none)
    if s != none and s != "" {
      v(subtitle-body-gap)
      pad(left: 0.8em, text(size: 9.5pt, s))
    }
    v(entry-gap)
  }
}

// ── Leadership and Service ────────────────────────────────────────────────────

#if data.at("leadership_service", default: ()).len() > 0 {
  section-rule("Leadership and Service")
  for entry in data.leadership_service {
    entry-header(
      entry.title,
      entry.organization,
      yr-range(entry.at("start_year", default: none), entry.at("end_year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: "")
    if s != "" {
      v(subtitle-body-gap)
      pad(left: 0.8em, text(s))
    }
    v(entry-gap)
  }
}

// ── Outreach ──────────────────────────────────────────────────────────────────

#if data.at("outreach", default: ()).len() > 0 {
  section-rule("Outreach")
  for entry in data.outreach {
    entry-header(
      entry.title,
      entry.organization,
      yr(entry.at("year", default: none)),
      entry.at("location", default: ""),
    )
    let s = entry.at("summary", default: none)
    if s != none and s != "" {
      v(subtitle-body-gap)
      pad(left: 0.8em, text(size: 9.5pt, s))
    }
    v(entry-gap)
  }
}

// ── Professional Presentations ────────────────────────────────────────────────

#let render-talks(talks) = {
  for talk in talks {
    v(0.25em, weak: true)
    pad(left: 1em)[
      #place(left, dx: -1em)[#sym.bullet]
      #emph(["] + talk.title + ["])
    ]
    for venue in talk.at("venues", default: ()) {
      let vname = venue.at("venue",    default: "")
      let loc   = venue.at("location", default: "")
      let year  = yr(venue.at("year",  default: none))
      let award = venue.at("award",    default: none)
      let emph2 = venue.at("emphasis", default: none)

      let parts = (vname,)
      if loc  != ""                    { parts.push(loc) }
      if year != ""                    { parts.push(year) }
      if award != none and award != "" { parts.push("(" + award + ")") }
      if emph2 != none and emph2 != "" { parts.push("(" + emph2 + ")") }

      v(item-gap, weak: true)
      pad(left: 2.2em)[
        #place(left, dx: -1.2em)[--]
        #parts.join(" | ")
      ]
    }
    v(0.3em)
  }
}

#let pres        = data.at("presentations",       default: (:))
#let invited     = pres.at("invited_talks",        default: ())
#let contributed = pres.at("contributed_talks",    default: ())
#let posters     = pres.at("contributed_posters",  default: ())

#if invited.len() > 0 or contributed.len() > 0 or posters.len() > 0 {
  section-rule("Professional Presentations")

  if invited.len() > 0 {
    text(weight: "bold", "Invited Talks")
    render-talks(invited)
  }

  if contributed.len() > 0 {
    v(0.5em)
    text(weight: "bold", "Contributed Talks")
    render-talks(contributed)
  }

  if posters.len() > 0 {
    v(0.5em)
    text(weight: "bold", "Contributed Posters")
    render-talks(posters)
  }
}

// ── Skills ────────────────────────────────────────────────────────────────────

#if data.at("skills", default: ()).len() > 0 {
  section-rule("Skills")
  for skill in data.skills {
    [*#(skill.label)*: #(skill.keywords)]
    linebreak()
    v(item-gap, weak: true)
  }
}
